# Generated by Django 5.1.3 on 2025-04-20 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='Номер')),
                ('image', models.ImageField(upload_to='floors/', verbose_name='План')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Этажи',
                'verbose_name_plural': 'этаж',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='Номер')),
                ('coords', models.TextField(verbose_name='Координаты')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='mysite.floor')),
            ],
            options={
                'verbose_name': 'Кабинеты',
                'verbose_name_plural': 'кабинет',
            },
        ),
    ]
