# Generated by Django 5.1.3 on 2025-04-21 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_floor_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name': 'этаж', 'verbose_name_plural': 'Этажи'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'кабинет', 'verbose_name_plural': 'Кабинеты'},
        ),
        migrations.AddField(
            model_name='room',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myworkroom', to=settings.AUTH_USER_MODEL, verbose_name='Лаборант кабинета'),
        ),
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myroom', to=settings.AUTH_USER_MODEL, verbose_name='Владелец кабинета'),
        ),
        migrations.AlterField(
            model_name='room',
            name='coords',
            field=models.TextField(max_length=250, verbose_name='Координаты'),
        ),
    ]
