# Generated by Django 5.1.3 on 2025-04-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_floor_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='room',
            name='lamps',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество ламп'),
        ),
        migrations.AddField(
            model_name='room',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='room',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AddField(
            model_name='room',
            name='windows',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество окон'),
        ),
        migrations.AddField(
            model_name='room',
            name='workspace_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество рабочих мест'),
        ),
        migrations.AlterField(
            model_name='room',
            name='coords',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Координаты'),
        ),
    ]
