# Generated by Django 5.1.3 on 2025-04-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_room_height_room_lamps_room_length_room_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='roommaps/', verbose_name='План'),
        ),
    ]
