# Generated by Django 5.1.3 on 2025-05-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_room_map_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='roomimages/', verbose_name='Фотография')),
                ('upload_at', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.ManyToManyField(related_name='room', to='mysite.cabinetphoto'),
        ),
    ]
