# Generated by Django 5.1.3 on 2025-05-03 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_cabinetphoto_room_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True)),
                ('attributes_schema', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Типы оборудования',
                'verbose_name_plural': 'Тип оборудования',
            },
        ),
        migrations.RemoveField(
            model_name='room',
            name='images',
        ),
        migrations.AddField(
            model_name='cabinetphoto',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='mysite.room'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('status', models.CharField(choices=[('working', 'Исправен'), ('repair', 'В ремонте'), ('broken', 'Неисправен')], default='working', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Состоит на учете')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('attributes', models.JSONField(default=dict, verbose_name='Характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.room', verbose_name='Кабинет')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.equipmenttype', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'оборудование',
            },
        ),
    ]
