# Generated by Django 5.1.3 on 2025-05-03 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_equipmenttype_remove_room_images_cabinetphoto_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cabinetphoto',
            options={'verbose_name': 'фото кабитнета', 'verbose_name_plural': 'Фото кабинетов'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.company'),
        ),
    ]
