# Generated by Django 5.1.3 on 2025-05-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_company_alter_cabinetphoto_options_equipment_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(default='equipmentimages/default.png', upload_to='equipmentimages/', verbose_name='Фотография'),
        ),
    ]
