# Generated by Django 5.1.3 on 2025-05-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_equipment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
