# Generated by Django 5.1.3 on 2025-05-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_remove_equipment_company_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='coords',
            field=models.CharField(max_length=100, null=True, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='attributes_schema',
            field=models.JSONField(default=dict, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
