# Generated by Django 5.1.3 on 2025-05-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_equipment_coords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
