# Generated by Django 5.1.3 on 2025-05-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_alter_equipmenttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=5, unique=True, verbose_name='Номер'),
        ),
    ]
