# Generated by Django 5.1.3 on 2025-05-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='coords',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Координаты'),
        ),
    ]
