# Generated by Django 5.1.3 on 2025-05-08 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_alter_equipment_coords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='mysite.room', verbose_name='Кабинет'),
        ),
        migrations.CreateModel(
            name='EquipmentMovementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=100, verbose_name='Откуда')),
                ('to_location', models.CharField(max_length=100, verbose_name='Куда')),
                ('moved_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата перемещения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='mysite.equipment')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто переместил')),
            ],
            options={
                'ordering': ['-moved_at'],
            },
        ),
    ]
