# Generated by Django 5.1.3 on 2025-05-08 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_alter_equipment_room_equipmentmovementlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentmovementlog',
            options={'ordering': ['-moved_at'], 'verbose_name': 'Лог перемещения', 'verbose_name_plural': 'Логи перемещения'},
        ),
        migrations.CreateModel(
            name='EquipmentDiscardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discard_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата списания')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('discard_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто списал')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discards', to='mysite.equipment')),
            ],
            options={
                'verbose_name': 'Лог списания',
                'verbose_name_plural': 'Логи списания',
                'ordering': ['-discard_at'],
            },
        ),
    ]
